name: ASCII Workflow

on:
  - push

jobs: 
    first_job:
        name:  my-new-job

        runs-on: ubuntu-latest
        steps:
            - name: Checkout Code
              uses: actions/checkout@v4

            - name: Visualize the content of the bash file
              run: cat ascii-script.sh