name: First Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs: 
  build:
    name: my-job-1
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: List and Read files
        run: |
          echo "My first GitHub Actions Job"
          ls -1
          cat dockerfile

      # Notify Slack on success
      - name: Notify Slack on Success
        if: success()
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        run: |
          curl -X POST -H 'Content-type: application/json' \
          --data '{"text":"✅ Job completed successfully!"}' $SLACK_WEBHOOK_URL

      # Notify Slack on failure
      - name: Notify Slack on Failure
        if: failure()
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        run: |
          curl -X POST -H 'Content-type: application/json' \
          --data '{"text":"❌ Job failed. Check the logs for details."}' $SLACK_WEBHOOK_URL
